### ISSUE TITLE
example

### ISSUE THREAD

**Issue by zmjones** [zmjones/rfss#1]
we need a new (preferably regression) example. i've looked through the last 2 years of the APSR and didn't see much. there is so much political theory in there! also they don't have a replication data policy like AJPS does.

i am not unopposed to keeping the state repression example of course, but one with interaction would nice of course.

**Comment by flinder** [comment]
I was looking for a bit now and I nothing jumped at me. I also thought about our old examples again. Since we have the papers split up right now maybe we can even keep both of our old examples in there.... Maybe we could make an argument with the survival forest to show how flexible the method is by just choosing a splitting criterion that is appropriate. I also had another idea of using government survival data to predict different kinds of termination (so classification). In the normal survival models all terminations are just treated as deaths (with some exceptions) but actually the terminations are quite different, sometimes the parliament gets dissolved, sometimes just the prime minister steps down, etc... So I think there could be an additional interesting substantive question in there. (Now that I write about it I wonder if this could even be a whole paper). What do you think? Sorry for bringing the same issues up again, but the reasons for just doing one new example are not as clear to me anymore. I think there is also a new data set on government survival that is a bit more recent

**Comment by zmjones** [comment]
No it is fine. I am not so much bothered by the apparent lack of interaction anymore. I think it would be fine to keep the same examples. Being able to send this off soon (sometime in November?) would be nice, as I have two major looming projects that I'd like to spend time on, in addition to our other piece.
